/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_nativecv_NativeFaceRecognizer */

#ifndef _Included_com_macaps_nativecv_NativeFaceRecognizer
#define _Included_com_macaps_nativecv_NativeFaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_nativecv_NativeFaceRecognizer
 * Method:    predictLBPH
 * Signature: (J[JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_macaps_nativecv_NativeFaceRecognizer_predictLBPH
  (JNIEnv *, jclass, jlong, jlongArray, jstring, jboolean);

/*
 * Class:     com_macaps_nativecv_NativeFaceRecognizer
 * Method:    predictORB
 * Signature: (J[JJ)I
 */
JNIEXPORT jint JNICALL Java_com_macaps_nativecv_NativeFaceRecognizer_predictORB
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     com_macaps_nativecv_NativeFaceRecognizer
 * Method:    predictCNN
 * Signature: (J[JJ[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_macaps_nativecv_NativeFaceRecognizer_predictCNN
  (JNIEnv *, jclass, jlong, jlongArray, jlong, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
