/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_nativecv_FacialPointDetector */

#ifndef _Included_com_macaps_nativecv_FacialPointDetector
#define _Included_com_macaps_nativecv_FacialPointDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_nativecv_FacialPointDetector
 * Method:    detectFLAND
 * Signature: (J[ILjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_macaps_nativecv_FacialPointDetector_detectFLAND
  (JNIEnv *, jclass, jlong, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
