/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_nativecv_NativeFilter */

#ifndef _Included_com_macaps_nativecv_NativeFilter
#define _Included_com_macaps_nativecv_NativeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_nativecv_NativeFilter
 * Method:    applyCLAHE
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_macaps_nativecv_NativeFilter_applyCLAHE
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_macaps_nativecv_NativeFilter
 * Method:    applyGamma
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_macaps_nativecv_NativeFilter_applyGamma
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
