/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_image_tester_LBPHAlgorithm */

#ifndef _Included_com_macaps_image_tester_LBPHAlgorithm
#define _Included_com_macaps_image_tester_LBPHAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_image_tester_LBPHAlgorithm
 * Method:    predict
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_macaps_image_1tester_LBPHAlgorithm_predict
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
