/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_image_tester_ContrastFilter */

#ifndef _Included_com_macaps_image_tester_ContrastFilter
#define _Included_com_macaps_image_tester_ContrastFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_image_tester_ContrastFilter
 * Method:    applyCLAHE
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_macaps_image_1tester_ContrastFilter_applyCLAHE
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_macaps_image_tester_ContrastFilter
 * Method:    applyGamma
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_macaps_image_1tester_ContrastFilter_applyGamma
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
