/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_image_tester_PointDetector */

#ifndef _Included_com_macaps_image_tester_PointDetector
#define _Included_com_macaps_image_tester_PointDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_image_tester_PointDetector
 * Method:    detectFLAND
 * Signature: (J[ILjava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_macaps_image_1tester_PointDetector_detectFLAND
  (JNIEnv *, jclass, jlong, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
