/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_image_tester_CNNAlgorithm */

#ifndef _Included_com_macaps_image_tester_CNNAlgorithm
#define _Included_com_macaps_image_tester_CNNAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_image_tester_CNNAlgorithm
 * Method:    predictCNN
 * Signature: (JJ[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_macaps_image_1tester_CNNAlgorithm_predictCNN
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
