/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_macaps_image_tester_ORBAlgorithm */

#ifndef _Included_com_macaps_image_tester_ORBAlgorithm
#define _Included_com_macaps_image_tester_ORBAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_macaps_image_tester_ORBAlgorithm
 * Method:    predict
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_macaps_image_1tester_ORBAlgorithm_predict
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
